### PR TITLE
Set editing profile index correctly when deleting profile

### LINKED ISSUE #1556: Invalid profile index error when creating and deleting profiles
image

**Steps to reproduce**:
1. Click `Add` to create a few profiles
2. Delete any profile except the last one, it will throw an error `Invalid profile index: x` where x is the last index of the profile list.

This error does not occur if you reload the page after creating new profiles.

List indexes should also be updated when a profile is deleted.

### PR DESCRIPTION
**Pull request by khaitruong922**
Fixes #1556

Let's call editing profile index `x` and deleted profile index `y`

Currently we does not handle:
-  `x < y`: The default profile and editing profile will be reset to the first profile, however when reload the page, it still has the value before reset. Additionally, the radio button does not represent the default profile correctly. Calling `_setProfileIndex` with the same `x` value will resolve this.
- `x > y`: The editing profile index is not shifted up, therefore it moves into below profile. When the editing profile is the last index, it will cause index error, and we cannot add more profiles after that. The issue happens because when we add a profile, the editing profile index is set to last index.

List indexes are also updated correctly after deletion.

### CODE REVIEW

**Review by jamesmaa — DISMISSED** [review]

File: ext/js/pages/settings/profile-controller.js [hunk 1]
```diff
@@ -261,6 +261,10 @@ export class ProfileController {
         // Update profile index
         if (settingsProfileIndex === profileIndex) {
```
Comment (jamesmaa) [inline ext/js/pages/settings/profile-controller.js:262]:
```suggestion
        if (settingsProfileIndex >= profileIndex) {
```
Isn't this math accounted for above? Line 231

```
if (profileCurrentNew >= profileIndex) {
            profileCurrentNew = Math.min(profileCurrentNew - 1, this._profiles.length - 1);
            modifications.push({
                action: 'set',
                path: 'profileCurrent',
                value: profileCurrentNew,
            });
        }
        
```

Comment (jamesmaa) [inline ext/js/pages/settings/profile-controller.js:262]: Also what's the difference between `settingsProfileIndex` and `profileIndex`?

**Review by jamesmaa — COMMENTED** [review]
Sorry have some q's

File: ext/js/pages/settings/profile-controller.js (hunk 1 above)
Comment (khaitruong922) [reply ext/js/pages/settings/profile-controller.js:262]: `settingsProfileIndex` is editing profile index, `profileIndex` is the index to be deleted. Maybe should rename this?

**Review by jamesmaa — APPROVED** [review]
yeah maybe renaming variables in this file as a separate PR would be good
